import React, { useRef } from "react"
import ReportHeader from "./ReportHeader"
import ChartsSection from "./ChartsSection"
import CO2Chart from "./CO2Chart"
import KPISection from "./KPISection"
import ImpactScore from "./ImpactScore"
import ROISimulator from "./ROISimulator"
import Benchmark from "./Benchmark"
import ShareLink from "./ShareLink"

export default function PDFExport({ data }) {
  const printRef = useRef()

  const handlePrint = () => {
    // Speichert den aktuellen Body
    const originalContents = document.body.innerHTML
    // Setzt das PDF-Div als Body
    document.body.innerHTML = printRef.current.innerHTML
    // Druckfenster öffnen
    window.print()
    // Original zurücksetzen und React neu laden
    document.body.innerHTML = originalContents
    window.location.reload()
  }

  return (
    <>
      <button
        onClick={handlePrint}
        className="bg-bgPurple40 text-white px-4 py-2 rounded shadow hover:opacity-90"
      >
        PDF Report herunterladen
      </button>

      {/* Verstecktes PDF Layout */}
      <div ref={printRef} className="hidden">
        <div className="bg-white text-black p-6 min-h-screen font-sans">
          {/* Header mit Logo */}
          <ReportHeader />

          {/* KPIs */}
          <section className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
            <KPISection data={data} />
          </section>

          {/* Diagramme */}
          <section className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
            <ChartsSection data={data} />
            <CO2Chart data={data} />
          </section>

          {/* ImpactScore, ROI, Benchmark, ShareLink */}
          <section className="grid grid-cols-1 lg:grid-cols-4 gap-6 mb-6">
            <ImpactScore data={data} />
            <ROISimulator data={data} />
            <Benchmark data={data} />
            <ShareLink data={data} />
          </section>

          {/* Optional Footer Hinweis */}
          <footer className="text-sm text-gray-600 mt-6">
            Generated by SIGN Impact Dashboard
          </footer>
        </div>
      </div>
    </>
  )
}
